const fs = require("node:fs");
const path = require("node:path");
const { test, expect, openTestDocument } = require("./test-fixture");

for (const length of [12, 20]) test(`free thread length accepts a ${length}mm driving dimension`, async ({ page }) => {
  const lines = ["L24", "L7"];
  await openTestDocument(page);
  const fixture = JSON.parse(fs.readFileSync(path.resolve(__dirname, "../fixtures/thread-length.jot2d"), "utf8"));
  expect(await page.evaluate(data => window.__jot2dTest.loadDocumentFixtureForDragTest(data, "thread.jot2d", { resetLoadedHistory: true }), fixture)).toMatchObject({ success: true });
  const before = await page.evaluate(() => window.__jot2dTest.serializedModelForTest());
  await page.evaluate(lines => window.__jot2dTest.selectGeometryIdsForTest({ lines }), lines);
  await page.click('[data-constraint="distance"]');
  const placement = await page.evaluate(() => window.__jot2dTest.worldClientPositionForTest({ x: 202, y: 125 }));
  await page.mouse.click(placement.x, placement.y);
  const input = page.locator("#dimensionValueInput");
  await expect(input).toBeVisible();
  const preview = await page.evaluate(() => window.__jot2dTest.serializedModelForTest());
  for (const key of ["points", "lines", "arcs", "circles", "constraints"]) expect(preview[key], key).toEqual(before[key]);
  await input.fill(String(length));
  await input.press("Enter");
  const saved = await page.evaluate(() => window.__jot2dTest.serializedModelForTest());
  const dimension = saved.constraints.find(c => c.type === "lineLineDistance" && [c.line1, c.line2].includes("L24") && [c.line1, c.line2].includes("L7"));
  expect(dimension).toMatchObject({ enabled: true, target: length });
  expect(dimension.readOnlyDimension).not.toBe(true);
  expect((await page.evaluate(() => window.__jot2dTest.constraintAnalysisForTest())).stable).toBe(true);
  const y = id => saved.points.find(p => p.id === saved.lines.find(l => l.id === id).p1).y;
  expect(Math.abs(y("L24") - y("L7"))).toBeCloseTo(length, 5);
  await page.click("#undoBtn");
  const undone = await page.evaluate(() => window.__jot2dTest.serializedModelForTest());
  for (const key of ["points", "lines", "arcs", "circles", "constraints"]) expect(undone[key], key).toEqual(before[key]);
  await page.click("#redoBtn");
  const redone = await page.evaluate(() => window.__jot2dTest.serializedModelForTest());
  expect(redone.constraints).toEqual(saved.constraints);
  expect(await page.evaluate(data => window.__jot2dTest.loadDocumentFixtureForDragTest(data), redone)).toMatchObject({ success: true });
  await page.evaluate(lines => window.__jot2dTest.selectGeometryIdsForTest({ lines }), lines);
  await page.click('[data-constraint="distance"]');
  await page.mouse.click(placement.x, placement.y);
  await expect(input).toBeHidden();
  const duplicate = await page.evaluate(() => window.__jot2dTest.serializedModelForTest());
  expect(duplicate.constraints.filter(c => c.readOnlyDimension)).toHaveLength(1);
});
