// Keep syntax validation below Windows shell command-length limits.
const { spawnSync } = require("node:child_process");
const path = require("node:path");
const files = [
  "src/editing/clipboard_transfer.js", "tests/unit/clipboard-transfer.test.js",
  "src/geometry/export_region.js", "src/rendering/canvas_export.js", "src/persistence/png_file.js", "src/commands/png_export_command.js", "tests/unit/png-export.test.js", "tests/e2e/png-export.spec.js",
  "src/ui/command_panel.js", "src/ui/derived_command_panel.js", "tests/e2e/command-panel.spec.js",
  "src/ui/tool_flyouts.js", "tests/e2e/tool-flyouts.spec.js",
  "tests/e2e/multiple-dimensions.spec.js",
  "tests/unit/property-selection.test.js",
  "src/editing/property_selection.js",
  "src/editing/appearance_editing.js",
  "src/commands/bulk_property_command.js", "src/commands/geometry_property_command.js", "src/commands/appearance_property_command.js", "src/commands/annotation_parameter_command.js", "src/commands/element_property_command.js", "src/commands/block_placement_command.js", "src/commands/instance_source_command.js", "src/commands/sketch_projection_command.js", "src/commands/geometry_instance_command.js", "src/commands/instance_transform_command.js", "src/commands/block_configuration_command.js", "src/commands/block_completion_command.js", "src/commands/block_definition_command.js", "src/commands/sketch_command.js", "src/commands/reference_image_interaction.js", "src/commands/annotation_drag.js", "src/commands/geometry_drag.js", "src/commands/dimension_drag.js", "tests/unit/dimension-drag.test.js", "src/commands/selection_rectangle.js", "tests/unit/selection-rectangle.test.js", "tests/unit/annotation-drag.test.js", "tests/unit/geometry-drag.test.js", "tests/unit/reference-image-interaction.test.js", "src/commands/sketch_deletion_command.js", "tests/unit/sketch-deletion-command.test.js", "tests/unit/sketch-command.test.js", "tests/unit/block-definition-command.test.js", "tests/unit/block-completion-command.test.js", "tests/unit/block-configuration-command.test.js", "tests/unit/instance-transform-command.test.js", "tests/unit/geometry-instance-command.test.js", "tests/unit/instance-source-command.test.js", "tests/unit/block-placement-command.test.js", "src/ui/properties_controller.js", "src/ui/properties_content.js", "src/editing/property_presentation.js", "tests/unit/property-presentation.test.js", "tests/unit/properties-controller.test.js", "tests/unit/appearance-property-command.test.js", "tests/unit/geometry-property-command.test.js",
  "tests/unit/appearance-controls.test.js",
  "src/ui/appearance_controls.js", "src/ui/property_rows.js", "src/ui/properties_view.js", "src/ui/block_view.js", "tests/unit/properties-view.test.js", "tests/unit/block-view.test.js",
  "src/ui/appearance_palette.js",
  "tests/unit/geometry-presentation.test.js", "tests/unit/selection-highlight.test.js",
  "src/editing/selection_highlight.js",
  "tests/unit/sketch-tree-presentation.test.js",
  "src/ui/sketch_tree_controller.js",
  "src/ui/sketch_tree_objects.js",
  "tests/unit/sketch-tree-view.test.js",
  "src/ui/sketch_tree_view.js",
  "src/rendering/interaction_overlay_renderer.js", "src/rendering/placement_preview_renderer.js", "src/rendering/authoring_preview_renderer.js", "src/rendering/offset_preview_renderer.js",
  "tests/unit/sketch-tree-hover.test.js", "tests/unit/point-usage.test.js", "tests/unit/operand-hit-query.test.js", "tests/unit/drawing-preview.test.js", "tests/unit/annotation-constraint-input.test.js", "tests/unit/instance-command-input.test.js", "tests/unit/drawing-command-input.test.js", "tests/unit/blank-canvas-gesture.test.js", "tests/unit/canvas-selection-interaction.test.js", "tests/unit/pointer-interaction-controller.test.js", "tests/unit/pointer-hover.test.js", "tests/unit/geometry-hit-query.test.js", "tests/unit/canvas-hover.test.js", "tests/unit/canvas-context-query.test.js", "tests/unit/canvas-context-menu.test.js", "tests/unit/annotation-spatial-query.test.js", "tests/unit/annotation-anchor-query.test.js", "tests/unit/annotation-command.test.js", "tests/unit/hatch-command.test.js", "tests/unit/offset-command.test.js",
  "src/geometry/offset_geometry.js",
  "src/editing/offset_construction.js",
  "src/commands/offset_command.js",
  "src/editing/offset_selection.js",
  "tests/unit/offset-selection.test.js",
  "src/commands/dimension_value_command.js",
  "tests/unit/dimension-value-command.test.js",
  "src/ui/dimension_input_controller.js",
  "tests/unit/dimension-input-controller.test.js",
  "src/ui/dimension_input_view.js",
  "tests/unit/dimension-input-view.test.js",
  "src/ui/command_cursor.js",
  "tests/unit/command-cursor.test.js",
  "src/commands/fillet_command.js",
  "tests/unit/fillet-command.test.js",
  "src/commands/line_command.js",
  "tests/unit/line-command.test.js",
  "src/commands/rectangle_command.js",
  "tests/unit/rectangle-command.test.js",
  "src/editing/transient_authoring.js",
  "tests/unit/transient-authoring.test.js",
  "src/commands/spline_edit_command.js", "src/commands/spline_command.js",
  "tests/unit/spline-command.test.js",
  "src/editing/spline_draft.js",
  "tests/unit/spline-draft.test.js",
  "src/ui/keyboard_interaction_controller.js", "src/ui/constraint_status_view.js", "src/ui/constraint_feedback.js", "src/ui/canvas_input_binding.js", "src/ui/canvas_navigation.js", "src/ui/pointer_move_scheduler.js",
  "tests/unit/pointer-move-scheduler.test.js", "tests/unit/canvas-navigation.test.js",
  "src/document/state.js",
  "tests/unit/document-state.test.js",
  "src/persistence/document_loading.js",
  "tests/unit/document-loading.test.js",
  "src/geometry/geometry_kernel.js",
  "src/geometry/geometry_ref.js",
  "src/geometry/spline_geometry.js",
  "src/geometry/hatch_region.js",
  "src/geometry/offset_chain.js",
  "src/persistence/constraint_codec_registry.js",
  "src/parameters/parameter_engine.js",
  "src/editing/edit_history.js", "src/editing/history_controller.js", "src/editing/history_restoration.js", "src/editing/document_application.js",
  "src/diagnostics/interaction_profiler.js",
  "src/ui/choice_dialog.js",
  "tests/e2e/choice-dialog.spec.js",
  "tests/e2e/dimension-prefix.spec.js",
  "tests/e2e/sketch-edit.spec.js",
  "tests/e2e/fixed-command.spec.js",
  "tests/e2e/block-geometry-fixed.spec.js",
  "app.js",
  "src/solver/constraint_solver.js",
  "tools/runtime-version.js",
  "tools/write-runtime-version.js",
  "tools/serve.js",
  "tools/generate-adversarial-drag-fixture.js",
  "playwright.config.js",
  "tests/fixtures/phase0-document.js",
  "tests/unit/constraint-codec-registry.test.js",
  "tests/unit/parameter-engine.test.js",
  "tests/unit/geometry-ref.test.js",
  "tests/unit/geometry-kernel.test.js",
  "tests/unit/spline-geometry.test.js",
  "tests/unit/hatch-query.test.js", "tests/unit/hatch-region.test.js",
  "tests/unit/offset-chain.test.js",
  "tests/unit/geometry-solver.test.js",
  "tests/e2e/test-fixture.js",
  "tests/e2e/phase0-characterization.spec.js",
  "tests/e2e/unified-ui.spec.js",
  "tests/e2e/hatching.spec.js",
  "tests/e2e/drawing-order.spec.js",
  "tests/e2e/reference-images.spec.js",
  "tests/e2e/spline.spec.js",
  "tests/e2e/free-instance.spec.js",
  "tests/e2e/sketch-projection.spec.js",
  "tests/e2e/centerline.spec.js",
  "tests/e2e/blocks.spec.js",
  "tests/e2e/drag-smoothness.spec.js",
  "tests/e2e/geometry-drag-smoothness.spec.js",
  "tests/e2e/constraint-drag-regressions.spec.js",
  "tests/e2e/adversarial-drag-fixture.spec.js",
  "tests/e2e/adversarial-authoring-performance.spec.js",
  "tests/unit/edit-history.test.js",
  "tests/unit/interaction-profiler.test.js",
  "src/document/appearance.js", "src/commands/hatch_command.js", "src/commands/annotation_command.js",
  "src/document/drawing_order.js", "src/editing/canvas_context_query.js", "src/editing/geometry_hit_query.js",
  "src/persistence/document_files.js", "src/commands/document_file_command.js",
  "tests/unit/appearance.test.js",
  "tests/unit/drawing-order.test.js",
  "tests/unit/document-files.test.js",
  "src/persistence/dimensions.js", "src/persistence/constraints.js",
  "tests/unit/constraint-persistence.test.js",
  "src/persistence/geometry.js",
  "tests/unit/geometry-persistence.test.js",
  "src/document/sketch_hierarchy.js",
  "tests/unit/sketch-hierarchy.test.js",
  "src/document/annotations.js",
  "src/document/hatches.js",
  "src/document/reference_images.js", "src/persistence/reference_image_import.js", "src/commands/reference_image_command.js",
  "tests/unit/document-elements.test.js",
  "src/persistence/document_snapshot.js",
  "tests/unit/document-snapshot.test.js",
  "src/editing/workspace.js", "src/editing/block_editor_session.js", "src/editing/block_editing_queries.js", "src/editing/block_selection_query.js", "tests/unit/block-selection-query.test.js", "tests/unit/block-editing-queries.test.js", "src/editing/block_definition_editing.js", "src/editing/block_history_snapshot.js", "tests/unit/block-definition-editing.test.js", "tests/unit/block-editor-session.test.js",
  "tests/unit/editing-workspace.test.js",
  "src/editing/selection.js", "src/editing/canvas_hover.js", "src/editing/point_usage.js", "src/commands/construction_command.js", "src/editing/draw_operation_lifecycle.js", "src/editing/drawing_preview.js", "src/commands/point_command.js", "src/editing/annotation_command_input.js", "src/editing/constraint_command_input.js", "src/editing/instance_command_input.js", "src/editing/drawing_command_input.js", "src/editing/blank_canvas_gesture.js", "src/editing/canvas_selection_interaction.js", "src/editing/canvas_press_query.js", "src/editing/pointer_interaction_controller.js", "src/editing/pointer_hover.js", "src/editing/rectangle_selection_query.js", "src/editing/geometry_drag_plan.js", "src/editing/geometry_drag_editing.js", "src/solver/geometry_drag_solver.js", "src/solver/solve_scope_query.js", "src/solver/sketch_solving.js", "src/constraints/reference_constraint_state.js", "src/constraints/constraint_redundancy.js", "src/constraints/constraint_analysis.js", "src/constraints/line_collapse_query.js", "src/constraints/sketch_projection_queries.js", "src/editing/sketch_projection_editing.js", "tests/unit/geometry-drag-plan.test.js", "tests/unit/geometry-drag-editing.test.js", "tests/unit/solve-scope-query.test.js", "tests/unit/sketch-solving.test.js", "tests/unit/reference-constraint-state.test.js", "tests/unit/constraint-redundancy.test.js", "tests/unit/constraint-analysis.test.js", "tests/unit/parameter-stabilization.test.js", "tests/unit/geometry-drag-solver.test.js", "tests/unit/rectangle-selection-query.test.js",
  "tests/unit/selection.test.js",
  "src/ui/application_settings.js",
  "tests/unit/application-settings.test.js",
  "src/constraints/references.js", "src/constraints/operand_hit_query.js",
  "tests/unit/constraint-references.test.js",
  "src/editing/sketch_context.js",
  "tests/unit/sketch-context.test.js",
  "tests/unit/module-loading.test.js",
  "src/constraints/dimension_queries.js",
  "src/parameters/namespace.js",
  "tests/unit/parameter-namespace.test.js",
  "src/geometry/objects.js", "src/geometry/annotation_anchor_query.js", "src/geometry/hatch_query.js",
  "src/geometry/instance_projection.js",
  "tests/unit/instance-projection.test.js",
  "src/document/block_catalog.js", "src/document/block_state.js",
  "src/geometry/block_projection.js",
  "tests/unit/block-layout.test.js", "tests/unit/block-projection.test.js",
  "src/geometry/read_model.js", "src/geometry/appearance_query.js",
  "tests/unit/geometry-read-model.test.js",
  "src/constraints/candidates.js", "src/constraints/operands.js",
  "tests/unit/constraint-candidates.test.js",
  "src/geometry/bounds.js", "src/geometry/block_layout.js", "src/geometry/reference_image_geometry.js", "src/rendering/drawing_bounds.js", "src/rendering/viewport.js",
  "tests/unit/drawing-bounds.test.js", "tests/unit/first-dimension-scaling.test.js", "tests/unit/viewport.test.js",
  "src/rendering/dimension_metrics.js",
  "tests/unit/dimension-metrics.test.js",
  "src/rendering/canvas_theme_colors.js", "src/rendering/geometry_presentation.js", "src/rendering/geometry_renderer.js",
  "tests/unit/interaction-overlay-renderer.test.js", "tests/unit/placement-preview-renderer.test.js", "tests/unit/authoring-preview-renderer.test.js", "tests/unit/geometry-renderer.test.js",
  "src/rendering/drawing_stack.js",
  "tests/unit/drawing-stack.test.js",
  "src/rendering/reference_image_renderer.js",
  "tests/unit/reference-image-renderer.test.js",
  "src/rendering/annotation_renderer.js", "src/rendering/annotation_spatial_query.js",
  "src/rendering/terminator_renderer.js", "tests/e2e/leader-appearance.spec.js",
  "tests/unit/annotation-renderer.test.js",
  "src/rendering/canvas_surface.js",
  "tests/unit/canvas-surface.test.js",
  "src/rendering/hatch_renderer.js",
  "tests/unit/hatch-renderer.test.js",
  "src/rendering/dimension_renderer.js",
  "tests/unit/dimension-renderer.test.js",
  "src/rendering/dimension_placement.js",
  "src/rendering/dimension_layout.js",
  "tests/unit/dimension-layout.test.js",
  "src/editing/slot_construction.js",
  "src/commands/slot_command.js",
  "tests/unit/slot-command.test.js",
  "src/editing/circular_construction.js",
  "src/commands/circular_commands.js",
  "tests/unit/circular-commands.test.js",
  "tests/e2e/circular-authoring.spec.js",
  "src/editing/geometry_ids.js",
  "src/editing/geometry_creation.js", "src/editing/first_dimension_scaling.js",
  "tests/unit/geometry-creation.test.js",
  "src/editing/checkpoint.js",
  "tests/unit/editing-checkpoint.test.js",
  "src/editing/trim_query.js",
  "tests/unit/trim-query.test.js",
  "src/editing/trim_editing.js",
  "tests/unit/trim-editing.test.js",
  "src/geometry/fillet_geometry.js",
  "src/editing/fillet_construction.js",
  "tests/unit/fillet-construction.test.js",
  "src/geometry/centerline_geometry.js",
  "src/editing/centerline_construction.js",
  "src/commands/centerline_command.js", "src/commands/circle_center_cross_command.js",
  "tests/unit/centerline-command.test.js",
  "src/editing/drawing_snap.js",
  "src/editing/snap_constraints.js",
  "tests/unit/drawing-snap.test.js",
  "src/ui/document_status_view.js", "src/ui/runtime_version_view.js", "src/ui/sidebar_controller.js", "src/ui/application_menus.js", "src/ui/canvas_context_menu.js", "src/ui/canvas_context_presentation.js",
  "tests/e2e/application-menus.spec.js",
  "src/parameters/dialog_draft.js",
  "tests/unit/parameter-dialog-draft.test.js",
  "src/ui/expression_input_view.js", "src/ui/parameter_dialog_view.js",
  "src/ui/parameter_dialog_controller.js",
  "tests/e2e/parameter-dialog-controller.spec.js",
  "src/parameters/application.js", "src/parameters/stabilization.js",
  "tests/unit/parameter-application.test.js",
  "src/parameters/block_propagation.js",
  "tests/unit/block-parameter-propagation.test.js",
  "src/constraints/rebinding.js",
  "tests/unit/constraint-rebinding.test.js",
  "src/persistence/block_ownership.js",
  "tests/unit/block-ownership.test.js",
  "src/persistence/block_definitions.js",
  "tests/unit/block-definition-persistence.test.js",
  "src/persistence/geometry_instances.js",
  "tests/unit/geometry-instance-persistence.test.js",
  "src/persistence/block_instances.js",
  "tests/unit/block-instance-persistence.test.js",
  "src/persistence/block_connections.js",
  "tests/unit/block-connections.test.js",
  "src/persistence/document_sequences.js",
  "tests/unit/document-sequences.test.js",
  "src/persistence/document_geometry.js",
  "tests/unit/document-geometry-persistence.test.js"
];
for (const file of files) {
  const result = spawnSync(process.execPath, ["--check", file], { cwd: path.resolve(__dirname, ".."), stdio: "inherit" });
  if (result.error) throw result.error;
  if (result.status !== 0) process.exit(result.status || 1);
}
console.log(`Syntax checked ${files.length} files`);
